<?php //echo $this->doctype()."\n"; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
	<head>
		<?php echo $this->headMeta()."\n"; ?>
		<?php echo $this->headTitle()."\n"; ?>				
		<?php echo $this->headScript() . "\n" ?>
	</head>
	<body>
            Layout 2 <?php echo $this->Comment; ?>
            <?php // var_dump ($_SERVER['PHP_SELF']); ?>
            <hr>
		<div id="content">
			<h1><?php echo $this->escape($this->title); ?></h1>
			<?php echo $this->layout()->content; ?>
		</div>
	</body>
</html>