<br /><br />
<div id="view-content">
    <table>
        <tr><th>id</th><th>Nom</th><th>Modificar</th><th>Eliminar</th></tr>
    <?php 
        foreach ($this->dpts as $dpt){
            
            echo "<tr><td>".$dpt->id."</td><td>".$dpt->nom."</td><td><a href='".$this->url(array('controller'=>'Departament','action'=>'modificar','id'=>$dpt->id))."'>Modificar</a></td><td><a href='".$this->url(array('controller'=>'Departament','action'=>'eliminar','id'=>$dpt->id))."'>Eliminar</a></td></tr>";
        }
    ?>
    </table>
    <a href="<?php echo $this->url(array('controller' => 'Departament','action'=>'nou'));?>">Afegir departament</a>
</div>