<br /><br />
<div id="view-content">
<a href="<?php echo $this->url(array('controller'=>'Empleat','action'=>'guardar'));?>">Nou empleat</a>
<br>
<a href="<?php echo $this->url(array('controller'=>'Login','action'=>'logout'));?>">Sortir</a>
<br>
<hr>
<br><br>
    <table>
    <?php foreach($this->emps as $emp) { ?>
    <tr>
        <td> <?php echo $emp['id']; ?></td>
        <td> <?php echo $emp['nom']; ?></td>
        <td> <?php echo $emp['nomdpt']; ?></td>
        <td> <a href="<?php echo $this->url(array('controller'=>'Empleat','action'=>'modificar', 'id'=>$emp['id']));?>">Modifica</a></td>
        <td> <a href="<?php echo $this->url(array('controller'=>'Empleat','action'=>'eliminar', 'id'=>$emp['id']));?>">Elimina</a></td>
        
    </tr>
    <?php } ?>
    </table>
    <br>
    
</div>