<br /><br />
<div id="view-content">
<a href="<?php echo $this->url(array('controller'=>'Departament','action'=>'guardar'));?>">Nou departament</a>
<br>
<a href="<?php echo $this->url(array('controller'=>'Empleat','action'=>'index'));?>">Llistat Empleats</a>
<br>
<a href="<?php echo $this->url(array('controller'=>'Login','action'=>'logout'));?>">Sortir</a>
<hr>
<br>
<a href="<?php echo $this->url(array('controller'=>'Info','action'=>'departaments'));?>">Empleats per departament</a>
<br>
<hr>
<br><br>
    <table>
    <?php foreach($this->dpts as $dpt) { ?>
    <tr>
        <td> <?php echo $dpt->id; ?></td>
        <td> <?php echo $dpt->nom; ?></td>
        <td> <a href="<?php echo $this->url(array('controller'=>'Departament','action'=>'modificar', 'id'=>$dpt->id));?>">Modifica</a></td>
        <td> <a href="<?php echo $this->url(array('controller'=>'Departament','action'=>'eliminar', 'id'=>$dpt->id));?>">Elimina</a></td>
        
    </tr>
    <?php } ?>
    </table>
    <br>
    
</div>